# Generated by Django 6.0.2 on 2026-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathogen',
            name='transmission',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
